### ISSUE TITLE
Datastore importing Arista full config slow

### ISSUE THREAD

**Issue by marshall-sg** [netmeld/netmeld#127]
**Describe the bug**
Importing an Arista config generated via `show running-config all` with the `nmdb-import-cisco` tool takes a considerable amount of time to parse.  In this case, timing is as being compared to similarly sized configs (order of minutes to 10's of minutes longer) and other parsers.  The exact reason is unclear and needs further investigation.  However given a ~2MB config file will generate a ~130MB debug file with the majority of it being boost debug output, there may be some erroneous looping occurring.

**To Reproduce**
Generate a config file via `show running-config all` and then parse.

**Expected behavior**
This needs examined more to determine if this can be improved or not.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by cmwill** [comment]
Attempted to replicate this issue. Even with verbosity at max on a config file that was ~2 MB (resulting in a ~149 MB debug file), it took about 70 seconds. About 30 with verbosity at 0. Whatever the issue is, it might not be one with the parser.

**Comment by marshall-sg** [comment]
So, with regards to this issue.  Some of my further testing towards the other issue allowed me to see the parser is done in ~5 seconds even for fairly large/complex configs (~70k config lines).  The majority (>80%) of time is spent on the DB transactions.  I am going to close this out as either #8 is probably the only way an improvement (if any) can be made to the overall performance issue.
