### ISSUE TITLE
Improve nmdl-list speed

### ISSUE THREAD

**Issue by marshall-sg** [netmeld/netmeld#139]
**Is your enhancement request related to a problem? Please describe.**
While not a show stopper, the Datalake tooling could have improvements made toward efficiency in regards to large repositories.  Specifically, if the repo has hundreds of files, the `nmdl-list` takes a considerable amount of time to simply list the data.

**Describe the solution you'd like**
The `nmdl-list` tool displays results faster for large repos.  While "faster" is relative, one would expect it would be on a similar order of the `ls` command.

**Describe alternatives you've considered**
None.

**Additional context**
Simple test, you can see an approximate order of magnitude performance impact between
```
(yes | nmdl-initialize && for i in {1..10}; do nmdl-insert --device-id test-$i /etc/hosts; done && time nmdl-list)>/dev/null
```
and
```
(yes | nmdl-initialize && for i in {1..100}; do nmdl-insert --device-id test-$i /etc/hosts; done && time nmdl-list)>/dev/null
```

Increasing the value only gets worse, probably about O(n^2) complexity.  This is most likely related to the `Git::setIngestToolData` function being called for every file regardless of whether that data is needed or not.  Considering the tooling has multiple flags to alter what is displayed (some require the additional data), the tooling probably needs to explicitly request that data when the flag is given rather than the handler just retrieving/adding it by default.

**Comment by cmwill** [comment]
Been looking into it more, don't see any ways to speed up actually gathering the ingest tool data so hopefully just only getting that data when necessary is enough.

**Comment by marshall-sg** [comment]
> Been looking into it more, don't see any ways to speed up actually gathering the ingest tool data so hopefully just only getting that data when necessary is enough.

I'm not sure what all you considered.  One thought which comes to my mind is instead of the way `setIngestToolData` calls `git log` for files individually, there is a singular call made at some point to gather all the log history.  Then the `setIngestToolData` function performs a lookup in a data map instead of performing the `git` query.  I wouldn't think performing a pre-fetch of the data would be too costly considering I can run it (e.g., `git log --pretty=format:"%B" --reverse`) fairly fast (i.e., sub-second) via the CLI.

**Comment by cmwill** [comment]
I just realized that I hadn't made a pull request for this yet.

After some refactoring and changing how git log was used, nmdl-list is running faster on my end.
