### ISSUE TITLE
ACL Processing for nmdb-import-cisco

### ISSUE THREAD

**Issue by marshall-sg** [netmeld/netmeld#4]
**Is your enhancement request related to a problem? Please describe.**
The `nmdb-import-cisco` tool should be able to appropriately parse ACLs.  Currently only the ASA one does this.

**Describe the solution you'd like**
The `nmdb-import-cisco` tool process ACL lists similar to how the ASA one does.

**Describe alternatives you've considered**
Attempted to process with the ASA parser, but it appears not to work appropriately.  Manual insertions was the only other option via the `nmdb-insert-ac` tool.

**Comment by cctechwiz** [comment]
Code complete. Troubleshooting regression test issues.

**Comment by marshall-sg** [comment]
I think you need to regress with bb56c23e9231e5a842f51ba176911188871edac5 installed.  That appears to be the last commit I was changing stuff that would impact the regression testing.

**Comment by marshall-sg** [comment]
I moved it back from done.  It needs an approved and merged pull request before it can be considered done.
