### ISSUE TITLE
Add a folder option for the `nmdb-graph-network` tool

### ISSUE THREAD

**Issue by marshall-sg** [netmeld/netmeld#58]
**Is your enhancement request related to a problem? Please describe.**
It would be good if we can specify the icon folder for the `nmdb-graph-network`.  This would allow the "default" location to be documented as well as allow alternate icons to be located elsewhere instead of having to install all to that default location.

**Describe the solution you'd like**
The tool could have an option like `--icon-folder`.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by iburres** [comment]
Code has been written to resolve this issue, but I need permission to create a "test" branch to push the changes for review.

**Comment by marshall-sg** [comment]
> Code has been written to resolve this issue, but I need permission to create a "test" branch to push the changes for review.

Though the issue you stated has been resolved, don't forget to create a pull request to flag when you are ready for review of the changes.

**Comment by iburres** [comment]
Ok, will do Marshall.
